export const EXPERIENCE_TYPE_REQUEST = "EXPERIENCE_TYPE_REQUEST"
export const EXPERIENCE_TYPE_SUCCESS = "EXPERIENCE_TYPE_SUCCESS"
export const EXPERIENCE_TYPE_FAIL = "EXPERIENCE_TYPE_FAIL"

export const EXPERIENCE_LOCATION_REQUEST = "EXPERIENCE_LOCATION_REQUEST"
export const EXPERIENCE_LOCATION_SUCCESS = "EXPERIENCE_LOCATION_SUCCESS"
export const EXPERIENCE_LOCATION_FAIL = "EXPERIENCE_LOCATION_FAIL"

export const EXPERIENCE_THEME_REQUEST = "EXPERIENCE_THEME_REQUEST"
export const EXPERIENCE_THEME_SUCCESS = "EXPERIENCE_THEME_SUCCESS"
export const EXPERIENCE_THEME_FAIL = "EXPERIENCE_THEME_FAIL"

export const EXPERIENCE_LANGUAGE_REQUEST = "EXPERIENCE_LANGUAGE_REQUEST"
export const EXPERIENCE_LANGUAGE_SUCCESS = "EXPERIENCE_LANGUAGE_SUCCESS"
export const EXPERIENCE_LANGUAGE_FAIL = "EXPERIENCE_LANGUAGE_FAIL"

export const EXPERIENCE_ISHOSTED_REQUEST = "EXPERIENCE_ISHOSTED_REQUEST"
export const EXPERIENCE_ISHOSTED_SUCCESS = "EXPERIENCE_ISHOSTED_SUCCESS"
export const EXPERIENCE_ISHOSTED_FAIL = "EXPERIENCE_ISHOSTED_FAIL"

export const EXPERIENCE_DESCRIPTION_REQUEST = "EXPERIENCE_DESCRIPTION_REQUEST"
export const EXPERIENCE_DESCRIPTION_SUCCESS = "EXPERIENCE_DESCRIPTION_SUCCESS"
export const EXPERIENCE_DESCRIPTION_FAIL = "EXPERIENCE_DESCRIPTION_FAIL"

export const EXPERIENCE_BROADCAST_REQUEST = "EXPERIENCE_BROADCAST_REQUEST"
export const EXPERIENCE_BROADCAST_SUCCESS = "EXPERIENCE_BROADCAST_SUCCESS"
export const EXPERIENCE_BROADCAST_FAIL = "EXPERIENCE_BROADCAST_FAIL"

export const EXPERIENCE_ITEMS_REQUEST = "EXPERIENCE_ITEMS_REQUEST"
export const EXPERIENCE_ITEMS_SUCCESS = "EXPERIENCE_ITEMS_SUCCESS"
export const EXPERIENCE_ITEMS_FAIL = "EXPERIENCE_ITEMS_FAIL"

export const EXPERIENCE_TITLE_REQUEST = "EXPERIENCE_TITLE_REQUEST"
export const EXPERIENCE_TITLE_SUCCESS = "EXPERIENCE_TITLE_SUCCESS"
export const EXPERIENCE_TITLE_FAIL = "EXPERIENCE_TITLE_FAIL"

export const EXPERIENCE_PRICE_REQUEST = "EXPERIENCE_PRICE_REQUEST"
export const EXPERIENCE_PRICE_SUCCESS = "EXPERIENCE_PRICE_SUCCESS"
export const EXPERIENCE_PRICE_FAIL = "EXPERIENCE_PRICE_FAIL"

export const EXPERIENCE_NUMBER_OF_HOURS_REQUEST = "EXPERIENCE_NUMBER_OF_HOURS_REQUEST"
export const EXPERIENCE_NUMBER_OF_HOURS_SUCCESS = "EXPERIENCE_NUMBER_OF_HOURS_SUCCESS"
export const EXPERIENCE_NUMBER_OF_HOURS_FAIL = "EXPERIENCE_NUMBER_OF_HOURS_FAIL"

export const EXPERIENCE_TIME_REQUEST = "EXPERIENCE_TIME_REQUEST"
export const EXPERIENCE_TIME_SUCCESS = "EXPERIENCE_TIME_SUCCESS"
export const EXPERIENCE_TIME_FAIL = "EXPERIENCE_TIME_FAIL"

export const EXPERIENCE_AVAILABILITY_REQUEST = "EXPERIENCE_AVAILABILITY_REQUEST"
export const EXPERIENCE_AVAILABILITY_SUCCESS = "EXPERIENCE_AVAILABILITY_SUCCESS"
export const EXPERIENCE_AVAILABILITY_FAIL = "EXPERIENCE_AVAILABILITY_FAIL"

export const EXPERIENCE_AGE_REQUEST = "EXPERIENCE_AGE_REQUEST"
export const EXPERIENCE_AGE_SUCCESS = "EXPERIENCE_AGE_SUCCESS"
export const EXPERIENCE_AGE_FAIL = "EXPERIENCE_AGE_FAIL"

export const EXPERIENCE_WORKING_REQUEST = "EXPERIENCE_WORKING_REQUEST"
export const EXPERIENCE_WORKING_SUCCESS = "EXPERIENCE_WORKING_SUCCESS"
export const EXPERIENCE_WORKING_FAIL = "EXPERIENCE_WORKING_FAIL"

export const EXPERIENCE_STORY_REQUEST = "EXPERIENCE_STORY_REQUEST"
export const EXPERIENCE_STORY_SUCCESS = "EXPERIENCE_STORY_SUCCESS"
export const EXPERIENCE_STORY_FAIL = "EXPERIENCE_STORY_FAIL"

export const EXPERIENCE_SKILLS_REQUEST = "EXPERIENCE_SKILLS_REQUEST"
export const EXPERIENCE_SKILLS_SUCCESS = "EXPERIENCE_SKILLS_SUCCESS"
export const EXPERIENCE_SKILLS_FAIL = "EXPERIENCE_SKILLS_FAIL"

export const EXPERIENCE_IMAGES_REQUEST = "EXPERIENCE_IMAGES_REQUEST"
export const EXPERIENCE_IMAGES_SUCCESS = "EXPERIENCE_IMAGES_SUCCESS"
export const EXPERIENCE_IMAGES_FAIL = "EXPERIENCE_IMAGES_FAIL"

export const EXPERIENCE_SUBMIT_REQUEST = "EXPERIENCE_SUBMIT_REQUEST"
export const EXPERIENCE_SUBMIT_SUCCESS = "EXPERIENCE_SUBMIT_SUCCESS"
export const EXPERIENCE_SUBMIT_FAIL = "EXPERIENCE_SUBMIT_FAIL"
export const EXPERIENCE_SUBMIT_RESET = "EXPERIENCE_SUBMIT_RESET"

export const EXPERIENCE_GET_REQUEST = "EXPERIENCE_GET_REQUEST"
export const EXPERIENCE_GET_SUCCESS = "EXPERIENCE_GET_SUCCESS"
export const EXPERIENCE_GET_FAIL = "EXPERIENCE_GET_FAIL"

export const EXPERIENCE_GET_POPULAR_IN_INDIA_REQUEST = "EXPERIENCE_GET_POPULAR_IN_INDIA_REQUEST"
export const EXPERIENCE_GET_POPULAR_IN_INDIA_SUCCESS = "EXPERIENCE_GET_POPULAR_IN_INDIA_SUCCESS"
export const EXPERIENCE_GET_POPULAR_IN_INDIA_FAIL = "EXPERIENCE_GET_POPULAR_IN_INDIA_FAIL"

export const EXPERIENCE_GET_COOKING_REQUEST = "EXPERIENCE_GET_COOKING_REQUEST"
export const EXPERIENCE_GET_COOKING_SUCCESS = "EXPERIENCE_GET_COOKING_SUCCESS"
export const EXPERIENCE_GET_COOKING_FAIL = "EXPERIENCE_GET_COOKING_FAIL"

export const EXPERIENCE_GET_LAST_WEEK_REQUEST = "EXPERIENCE_GET_LAST_WEEK_REQUEST"
export const EXPERIENCE_GET_LAST_WEEK_SUCCESS = "EXPERIENCE_GET_LAST_WEEK_SUCCESS"
export const EXPERIENCE_GET_LAST_WEEK_FAIL = "EXPERIENCE_GET_LAST_WEEK_FAIL"

export const EXPERIENCE_GET_FILTERED_RESULT_REQUEST = "EXPERIENCE_GET_FILTERED_RESULT_REQUEST"
export const EXPERIENCE_GET_FILTERED_RESULT_SUCCESS = "EXPERIENCE_GET_FILTERED_RESULT_SUCCESS"
export const EXPERIENCE_GET_FILTERED_RESULT_FAIL = "EXPERIENCE_GET_FILTERED_RESULT_FAIL"


export const EXPERIENCE_GET_MAIN_FILTER_RESULT_REQUEST = "EXPERIENCE_GET_MAIN_FILTER_RESULT_REQUEST"
export const EXPERIENCE_GET_MAIN_FILTER_RESULT_SUCCESS = "EXPERIENCE_GET_MAIN_FILTER_RESULT_SUCCESS"
export const EXPERIENCE_GET_MAIN_FILTER_RESULT_FAIL = "EXPERIENCE_GET_MAIN_FILTER_RESULT_FAIL"

export const EXPERIENCE_GET_EXPERIENCEBYID_RESULT_REQUEST = "EXPERIENCE_GET_EXPERIENCEBYID_RESULT_REQUEST"
export const EXPERIENCE_GET_EXPERIENCEBYID_RESULT_SUCCESS = "EXPERIENCE_GET_EXPERIENCEBYID_RESULT_SUCCESS"
export const EXPERIENCE_GET_EXPERIENCEBYID_RESULT_FAIL = "EXPERIENCE_GET_EXPERIENCEBYID_RESULT_FAIL"

export const EXPERIENCE_CREATE_REVIEW_REQUEST = "EXPERIENCE_CREATE_REVIEW_REQUEST"
export const EXPERIENCE_CREATE_REVIEW_SUCCESS = "EXPERIENCE_CREATE_REVIEW_SUCCESS"
export const EXPERIENCE_CREATE_REVIEW_FAIL = "EXPERIENCE_CREATE_REVIEW_FAIL"
export const EXPERIENCE_CREATE_REVIEW_RESET = "EXPERIENCE_CREATE_REVIEW_RESET"

export const EXPERIENCE_GET_SIMILAR_EXPERIENCE_REQUEST = "EXPERIENCE_GET_SIMILAR_EXPERIENCE_REQUEST"
export const EXPERIENCE_GET_SIMILAR_EXPERIENCE_SUCCESS = "EXPERIENCE_GET_SIMILAR_EXPERIENCE_SUCCESS"
export const EXPERIENCE_GET_SIMILAR_EXPERIENCE_FAIL = "EXPERIENCE_GET_SIMILAR_EXPERIENCE_FAIL"

export const EXPERIENCE_GET_TOP_RATED_EXPERIENCE_REQUEST = "EXPERIENCE_GET_TOP_RATED_EXPERIENCE_REQUEST"
export const EXPERIENCE_GET_TOP_RATED_EXPERIENCE_SUCCESS = "EXPERIENCE_GET_TOP_RATED_EXPERIENCE_SUCCESS"
export const EXPERIENCE_GET_TOP_RATED_EXPERIENCE_FAIL = "EXPERIENCE_GET_TOP_RATED_EXPERIENCE_FAIL"

export const EXPERIENCE_GET_TEAM_EXPERIENCE_REQUEST = "EXPERIENCE_GET_TEAM_EXPERIENCE_REQUEST"
export const EXPERIENCE_GET_TEAM_EXPERIENCE_SUCCESS = "EXPERIENCE_GET_TEAM_EXPERIENCE_SUCCESS"
export const EXPERIENCE_GET_TEAM_EXPERIENCE_FAIL = "EXPERIENCE_GET_TEAM_EXPERIENCE_FAIL"
