export const EXPERIENCE_TYPE_REQUEST = "EXPERIENCE_TYPE_REQUEST"
export const EXPERIENCE_TYPE_SUCCESS = "EXPERIENCE_TYPE_SUCCESS"
export const EXPERIENCE_TYPE_FAIL = "EXPERIENCE_TYPE_FAIL"

export const EXPERIENCE_LOCATION_REQUEST = "EXPERIENCE_LOCATION_REQUEST"
export const EXPERIENCE_LOCATION_SUCCESS = "EXPERIENCE_LOCATION_SUCCESS"
export const EXPERIENCE_LOCATION_FAIL = "EXPERIENCE_LOCATION_FAIL"