export const HOST_ADD_REQUEST = "HOST_ADD_REQUEST"
export const HOST_ADD_SUCCESS = "HOST_ADD_SUCCESS"
export const HOST_ADD_FAIL = "HOST_ADD_FAIL"
export const HOST_EMPTY = "HOST_EMPTY"

export const HOST_GET_REQUEST = "HOST_GET_REQUEST"
export const HOST_GET_SUCCESS = "HOST_GET_SUCCESS"
export const HOST_GET_FAIL = "HOST_GET_FAIL"

export const HOST_GET_TOP_RATED_REQUEST = "HOST_GET_TOP_RATED_REQUEST"
export const HOST_GET_TOP_RATED_SUCCESS = "HOST_GET_TOP_RATED_SUCCESS"
export const HOST_GET_TOP_RATED_FAIL = "HOST_GET_TOP_RATED_FAIL"
export const HOST_GET_TOP_RATED_RESET = "HOST_GET_TOP_RATED_RESET"

export const HOST_GET_LOW_PRICE_REQUEST = "HOST_GET_LOW_PRICE_REQUEST"
export const HOST_GET_LOW_PRICE_SUCCESS = "HOST_GET_LOW_PRICE_SUCCESS"
export const HOST_GET_LOW_PRICE_FAIL = "HOST_GET_LOW_PRICE_FAIL"

export const HOST_GET_HIGH_PRICE_REQUEST = "HOST_GET_HIGH_PRICE_REQUEST"
export const HOST_GET_HIGH_PRICE_SUCCESS = "HOST_GET_HIGH_PRICE_SUCCESS"
export const HOST_GET_HIGH_PRICE_FAIL = "HOST_GET_HIGH_PRICE_FAIL"

export const HOST_GET_NUMBER_OF_BEDROOMS_REQUEST = "HOST_GET_NUMBER_OF_BEDROOMS_REQUEST"
export const HOST_GET_NUMBER_OF_BEDROOMS_SUCCESS = "HOST_GET_NUMBER_OF_BEDROOMS_SUCCESS"
export const HOST_GET_NUMBER_OF_BEDROOMS_FAIL = "HOST_GET_NUMBER_OF_BEDROOMS_FAIL"

export const HOST_GET_SEARCH_RESULTS_REQUEST = "HOST_GET_SEARCH_RESULTS_REQUEST"
export const HOST_GET_SEARCH_RESULTS_SUCCESS = "HOST_GET_SEARCH_RESULTS_SUCCESS"
export const HOST_GET_SEARCH_RESULTS_FAIL = "HOST_GET_SEARCH_RESULTS_FAIL"

export const HOST_GET_SEARCH_HEADER_RESULTS_REQUEST = "HOST_GET_SEARCH_HEADER_RESULTS_REQUEST"
export const HOST_GET_SEARCH_HEADER_RESULTS_SUCCESS = "HOST_GET_SEARCH_HEADER_RESULTS_SUCCESS"
export const HOST_GET_SEARCH_HEADER_RESULTS_FAIL = "HOST_GET_SEARCH_HEADER_RESULTS_FAIL"
export const HOST_GET_SEARCH_HEADER_RESULTS_RESET = "HOST_GET_SEARCH_HEADER_RESULTS_RESET"

export const HOST_GET_SEARCH_RESULTS_FOR_DATES_REQUEST = "HOST_GET_SEARCH_RESULTS_FOR_DATES_REQUEST"
export const HOST_GET_SEARCH_RESULTS_FOR_DATES_SUCCESS = "HOST_GET_SEARCH_RESULTS_FOR_DATES_SUCCESS"
export const HOST_GET_SEARCH_RESULTS_FOR_DATES_FAIL = "HOST_GET_SEARCH_RESULTS_FOR_DATES_FAIL"

export const HOST_GET_SUITED_RESULTS_REQUEST = "HOST_GET_SUITED_RESULTS_REQUEST"
export const HOST_GET_SUITED_RESULTS_SUCCESS = "HOST_GET_SUITED_RESULTS_SUCCESS"
export const HOST_GET_SUITED_RESULTS_FAIL = "HOST_GET_SUITED_RESULTS_FAIL"

export const HOSTED_PLACE_DETAILS_REQUEST = "HOSTED_PLACE_DETAILS_REQUEST"
export const HOSTED_PLACE_DETAILS_SUCCESS = "HOSTED_PLACE_DETAILS_SUCCESS"
export const HOSTED_PLACE_DETAILS_FAIL = "HOSTED_PLACE_DETAILS_FAIL"

export const HOSTED_PLACE_RATING_REQUEST = "HOSTED_PLACE_RATING_REQUEST"
export const HOSTED_PLACE_RATING_SUCCESS = "HOSTED_PLACE_RATING_SUCCESS"
export const HOSTED_PLACE_RATING_FAIL = "HOSTED_PLACE_RATING_FAIL"
export const HOSTED_PLACE_RATING_RESET = "HOSTED_PLACE_RATING_RESET"

export const HOSTED_PLACE_BOOKING_REQUEST = "HOSTED_PLACE_BOOKING_REQUEST"
export const HOSTED_PLACE_BOOKING_SUCCESS = "HOSTED_PLACE_BOOKING_SUCCESS"
export const HOSTED_PLACE_BOOKING_FAIL = "HOSTED_PLACE_BOOKING_FAIL"
export const HOSTED_PLACE_BOOKING_RESET = "HOSTED_PLACE_BOOKING_RESET"


export const HOSTED_PLACE_UNIQUE_STAYS_REQUEST = "HOSTED_PLACE_UNIQUE_STAYS_REQUEST"
export const HOSTED_PLACE_UNIQUE_STAYS_SUCCESS = "HOSTED_PLACE_UNIQUE_STAYS_SUCCESS"
export const HOSTED_PLACE_UNIQUE_STAYS_FAIL = "HOSTED_PLACE_UNIQUE_STAYS_FAIL"
export const HOSTED_PLACE_UNIQUE_STAYS_RESET = "HOSTED_PLACE_UNIQUE_STAYS_RESET"

export const HOSTED_PLACE_ENTIRE_HOMES_REQUEST = "HOSTED_PLACE_ENTIRE_HOMES_REQUEST"
export const HOSTED_PLACE_ENTIRE_HOMES_SUCCESS = "HOSTED_PLACE_ENTIRE_HOMES_SUCCESS"
export const HOSTED_PLACE_ENTIRE_HOMES_FAIL = "HOSTED_PLACE_ENTIRE_HOMES_FAIL"
export const HOSTED_PLACE_ENTIRE_HOMES_RESET = "HOSTED_PLACE_ENTIRE_HOMES_RESET"

export const HOSTED_PLACE_COTTAGES_REQUEST = "HOSTED_PLACE_COTTAGES_REQUEST"
export const HOSTED_PLACE_COTTAGES_SUCCESS = "HOSTED_PLACE_COTTAGES_SUCCESS"
export const HOSTED_PLACE_COTTAGES_FAIL = "HOSTED_PLACE_COTTAGES_FAIL"
export const HOSTED_PLACE_COTTAGES_RESET = "HOSTED_PLACE_COTTAGES_RESET"

export const HOSTED_PLACE_CREATEDBY_REQUEST = "HOSTED_PLACE_CREATEDBY_REQUEST"
export const HOSTED_PLACE_CREATEDBY_SUCCESS = "HOSTED_PLACE_CREATEDBY_SUCCESS"
export const HOSTED_PLACE_CREATEDBY_FAIL = "HOSTED_PLACE_CREATEDBY_FAIL"

export const HOSTED_PLACE_UPDATE_DETAILS_REQUEST = "HOSTED_PLACE_UPDATE_DETAILS_REQUEST"
export const HOSTED_PLACE_UPDATE_DETAILS_SUCCESS = "HOSTED_PLACE_UPDATE_DETAILS_SUCCESS"
export const HOSTED_PLACE_UPDATE_DETAILS_FAIL = "HOSTED_PLACE_UPDATE_DETAILS_FAIL"

export const HOSTED_PLACE_DELETE_REQUEST = "HOSTED_PLACE_DELETE_REQUEST"
export const HOSTED_PLACE_DELETE_SUCCESS = "HOSTED_PLACE_DELETE_SUCCESS"
export const HOSTED_PLACE_DELETE_FAIL = "HOSTED_PLACE_DELETE_FAIL"
