export const HOST_ADD_REQUEST = "HOST_ADD_REQUEST"
export const HOST_ADD_SUCCESS = "HOST_ADD_SUCCESS"
export const HOST_ADD_FAIL = "HOST_ADD_FAIL"
export const HOST_EMPTY = "HOST_EMPTY"

export const HOST_GET_REQUEST = "HOST_GET_REQUEST"
export const HOST_GET_SUCCESS = "HOST_GET_SUCCESS"
export const HOST_GET_FAIL = "HOST_GET_FAIL"

export const HOST_GET_TOP_RATED_REQUEST = "HOST_GET_TOP_RATED_REQUEST"
export const HOST_GET_TOP_RATED_SUCCESS = "HOST_GET_TOP_RATED_SUCCESS"
export const HOST_GET_TOP_RATED_FAIL = "HOST_GET_TOP_RATED_FAIL"

export const HOSTED_PLACE_DETAILS_REQUEST = "HOSTED_PLACE_DETAILS_REQUEST"
export const HOSTED_PLACE_DETAILS_SUCCESS = "HOSTED_PLACE_DETAILS_SUCCESS"
export const HOSTED_PLACE_DETAILS_FAIL = "HOSTED_PLACE_DETAILS_FAIL"

export const HOSTED_PLACE_RATING_REQUEST = "HOSTED_PLACE_RATING_REQUEST"
export const HOSTED_PLACE_RATING_SUCCESS = "HOSTED_PLACE_RATING_SUCCESS"
export const HOSTED_PLACE_RATING_FAIL = "HOSTED_PLACE_RATING_FAIL"
export const HOSTED_PLACE_RATING_RESET = "HOSTED_PLACE_RATING_RESET"