export const SAVE_HOSTEDPLACE = "SAVE_HOSTEDPLACE"
export const REMOVE_HOSTEDPLACE = "REMOVE_HOSTEDPLACE"

export const SAVE_EXPERIENCE = "SAVE_EXPERIENCE"
export const REMOVE_EXPERIENCE = "REMOVE_EXPERIENCE"


